<div class="worksitem">
        <div class="worksimg">
            <div class="workimgbody"><a href="[field:arcurl/]"  title="[field:title/]" target="_blank" ><img src="{dede:list pagesize="24"}" width="220" height="150" /></a>
                <div class="workimgtxt"><a href="[field:arcurl/]"  title="[field:title/]" target="_blank" ><span>READ MORE</span></a><span class="witnum">.01</span></div>
            </div>
        </div>
        <div class="workstxt"><a href="[field:arcurl/]"   title="[field:title/]" target="_blank" ><strong>[field:title/]</strong></a>
            <p>Date:2015-04-09<br />
                <span>所属分类：<a href="[field:arcurl/]"  title="[field:title/]" target="_blank" >[field:typename/]</a></span></p>
        </div>
        <div class="wizoom"><img src="/skin/default/images/wizoom.png" width="43" height="47" /></div>
    </div>