<?php
$z[0]=Array("pubdate","",38,81);
$z[0][4]['function']="MyDate('m',@me)";
$z[1]=Array("pubdate","",88,131);
$z[1][4]['function']="MyDate('Y',@me)";
$z[2]=Array("arcurl","",163,178);
$z[3]=Array("title","",180,194);
$z[4]=Array("typename","",218,235);
$z[5]=Array("infos","",436,450);
$z[6]=Array("arcurl","",480,495);
$z[7]=Array("title","",504,518);
$z[8]=Array("picname","",530,546);
$z[9]=Array("title","",578,592);

?>