<?php
$z[0]=Array("pubdate","",8,55);
$z[0][4]['function']="MyDate('Y-m-d',@me)";
$z[1]=Array("pubdate","",93,136);
$z[1][4]['function']="MyDate('m',@me)";
$z[2]=Array("pubdate","",143,186);
$z[2][4]['function']="MyDate('Y',@me)";
$z[3]=Array("arcurl","",218,233);
$z[4]=Array("title","",235,249);
$z[5]=Array("typename","",273,290);
$z[6]=Array("infos","",491,505);
$z[7]=Array("arcurl","",535,550);
$z[8]=Array("title","",559,573);
$z[9]=Array("picname","",585,601);
$z[10]=Array("title","",633,647);

?>