<?php
$z[0]=Array("wangzhi","\r\n",0,156);
$z[0][4]['itemname']="案例网址";
$z[0][4]['autofield']="1";
$z[0][4]['notsend']="0";
$z[0][4]['type']="text";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="0";
$z[0][4]['default']="";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("body","	\r\n",158,315);
$z[1][4]['itemname']="文章内容";
$z[1][4]['autofield']="0";
$z[1][4]['notsend']="0";
$z[1][4]['type']="htmltext";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="1";
$z[1][4]['default']="";
$z[1][4]['maxlength']="";
$z[1][4]['page']="split";

?>