<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1543,1578);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1694,1723);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n",1794,1968);
$z[4][4]['type']="son";
$z[4][4]['currentstyle']="<li><a href='~typelink~' id='active'>~typename~</a></li>";
$z[5]=Array("field","",2019,2040);
$z[5][4]['name']="content";
$z[6]=Array("include","",2057,2094);
$z[6][4]['filename']="footer.htm";

?>