<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1543,1578);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1694,1723);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n",1794,1968);
$z[4][4]['type']="son";
$z[4][4]['currentstyle']="<li><a href='~typelink~' id='active'>~typename~</a></li>";
$z[5]=Array("field","",2166,2187);
$z[5][4]['name']="picname";
$z[6]=Array("field","",2288,2307);
$z[6][4]['name']="title";
$z[7]=Array("field","",2327,2347);
$z[7][4]['name']="zhiwei";
$z[8]=Array("field","",2367,2386);
$z[8][4]['name']="xueli";
$z[9]=Array("field","",2412,2430);
$z[9][4]['name']="byxy";
$z[10]=Array("field","",2450,2469);
$z[10][4]['name']="weibo";
$z[11]=Array("prenext","",2650,2675);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",2735,2761);
$z[12][4]['get']="next";
$z[13]=Array("include","",2887,2924);
$z[13][4]['filename']="footer.htm";

?>