
<field:title itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:title>

<field:mycall itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mycall>

<field:qq itemname="QQ" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:qq>

<field:company itemname="公司或个人建站：" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:saytext itemname="详细内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:saytext>
