<li>
<dl id="news_l"><em>Date</em><b>02</b><i>2015</i></dl>
<span>
<h3><a href="[field:arcurl/]">[field:title/]</a></h3>
<em>分类：[field:typename/]<br>浏览次数：<script src="{dede:field name='phpurl'/}/count.php?view=yes&aid={dede:field name='id'/}&mid={dede:field name='mid'/}" type='text/javascript' language="javascript"></script></em>
<p>[field:infos/]…</p>
</span>
<s><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" width="175" height="110" alt="[field:title/]"></a></s>
</li>