<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1543,1578);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1696,1725);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1864,1885);
$z[4][4]['name']="content";
$z[5]=Array("include","",1914,1951);
$z[5][4]['filename']="footer.htm";

?>