<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1529,1564);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1680,1709);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n",1780,1954);
$z[4][4]['type']="son";
$z[4][4]['currentstyle']="<li><a href='~typelink~' id='active'>~typename~</a></li>";
$z[5]=Array("include","",5054,5091);
$z[5][4]['filename']="footer.htm";

?>