<?php
$z[0]=Array("global","",88,114);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",1439,1465);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",1535,1561);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n",1628,1730);
$z[3][4]['type']="top";
$z[4]=Array("arclist","\r\n<li>\r\n<a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\" class=\"tagImg1\"><img src=\"[field:picname/]\" width=\"300\" height=\"204\" alt=\"[field:title/]\"></a>\r\n<div class=\"tagDiv1\">\r\n<span>[field:title/]</span>\r\n<p class=\"tagP2\">[field:infos/]...</p>\r\n<p class=\"tagP3\"><a href=\"[field:arcurl/]\">查看该案例</a></p>\r\n</div>\r\n</li>\r\n",7284,7718);
$z[4][4]['typeid']="2";
$z[4][4]['row']="12";
$z[4][4]['titlelen']="20";
$z[4][4]['infolen']="200";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\"><img src=\"[field:picname/]\" width=\"175\" height=\"110\" alt=\"[field:title/]\"><span>[field:title/]</span>[field:infos/]...</a>\r\n</li>\r\n",8802,9093);
$z[5][4]['typeid']="6";
$z[5][4]['row']="5";
$z[5][4]['titlelen']="20";
$z[5][4]['infolen']="500";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("channel","\r\n<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n",9368,9461);
$z[6][4]['type']="top";
$z[7]=Array("global","",9875,9897);
$z[7][4]['name']="cfg_add";
$z[8]=Array("flink","[field:link /]",11715,11776);
$z[8][4]['linktype']="2";
$z[8][4]['row']="24";
$z[9]=Array("global","",11837,11863);
$z[9][4]['name']="cfg_banquan";
$z[10]=Array("global","",11939,11963);
$z[10][4]['name']="cfg_beian";

?>