<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1563,1598);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1714,1743);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n",1830,2004);
$z[4][4]['type']="son";
$z[4][4]['currentstyle']="<li><a href='~typelink~' id='active'>~typename~</a></li>";
$z[5]=Array("list","\r\n	<div class=\"worksitem\">\r\n        <div class=\"worksimg\">\r\n            <div class=\"workimgbody\"><a href=\"[field:arcurl/]\"  title=\"[field:title/]\" target=\"_blank\" ><img src=\"[field:picname/]\" width=\"220\" height=\"150\" /></a>\r\n                <div class=\"workimgtxt\"><a href=\"[field:arcurl/]\"  title=\"[field:title/]\" target=\"_blank\" ><span>READ MORE</span></a><span class=\"witnum\">.01</span></div>\r\n            </div>\r\n        </div>\r\n        <div class=\"workstxt\"><a href=\"[field:arcurl/]\"   title=\"[field:title/]\" target=\"_blank\" ><strong>[field:title/]</strong></a>\r\n            <p>Date:2015-04-09<br />\r\n                <span>所属分类：<a href=\"[field:arcurl/]\"  title=\"[field:title/]\" target=\"_blank\" >[field:typename/]</a></span></p>\r\n        </div>\r\n        <div class=\"wizoom\"><img src=\"/skin/default/images/wizoom.png\" width=\"43\" height=\"47\" /></div>\r\n    </div>\r\n",2125,3038);
$z[5][4]['pagesize']="24";
$z[6]=Array("pagelist","",3082,3148);
$z[6][4]['listitem']="index,pre,next,pageno,end";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",3183,3220);
$z[7][4]['filename']="footer.htm";

?>