<?php
$z[0]=Array("field","",64,83);
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1563,1598);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1714,1743);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n",1814,1988);
$z[4][4]['type']="son";
$z[4][4]['currentstyle']="<li><a href='~typelink~' id='active'>~typename~</a></li>";
$z[5]=Array("list","\r\n<li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"188\" height=\"290\" alt=\"[field:title/]\"><span><em>[field:title/]</em><i>职位：[field:zhiwei/]</i></span></a></li>\r\n",2078,2333);
$z[5][4]['pagesize']="15";
$z[5][4]['addfields']="zhiwei";
$z[5][4]['channelid']="19";
$z[6]=Array("pagelist","",2376,2442);
$z[6][4]['listitem']="index,pre,next,pageno,end";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2479,2516);
$z[7][4]['filename']="footer.htm";

?>